language: node_js

sudo: false

node_js:
  - "8"

install:
  - npm install

script:
  - npm test
  - ./install.sh # move up to install
#  - chmod a+x "./scripts/ci-tests.sh"
#  - "./scripts/ci-tests.sh"
